[build]
  publish = "frontend/site"

[[redirects]]
  from = "/api/*"
  to = "https://kanglei.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
